title: Wolverine2k.GitHub.io
description: For creating pages. Help from (https://help.github.com/articles/creating-pages-with-the-automatic-generator/)
google_analytics: 
show_downloads: true
theme: jekyll-theme-hacker

gems:
  - jekyll-mentions
